[package]
authors = ['Konomi Dev']
description = 'FRAME pallet for ocw'
edition = '2018'
license = 'Unlicense'
name = 'pallet-oracle'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.1" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.1" }
serde = { version = "1.0.119", optional = true }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.1" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.1" }

log = "0.4.13"

pallet-currencies = { path = '../currencies', default-features = false, version = '3.0.0'}
pallet-traits = { path = '../traits', default-features = false, version = '3.0.0'}
polkadot-parachain-primitives = { default-features = false, path = '../../primitives', version = '0.1.0'}

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"serde",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-currencies/std",
]
