version: '3'

volumes:
  konomi-rococo: {}

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf.multi:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  konomi-rococo:
    image: asia.gcr.io/dev-env-312104/konomi-rococo:v0.0.1
    volumes:
      - konomi-rococo:/tmp/konomi-rococo
    command: "--base-path /tmp/konomi-rococo --parachain-id 18403 --port 40337 --ws-port 9944 --ws-external --rpc-cors all --rpc-port 9929 -- --execution wasm --chain rococo --port 30337"

  node-helper:
    image: asia.gcr.io/dev-env-312104/node-helper:v0.0.1
