version: '3'

volumes:
  konomi-relay-1: {}
  konomi-relay-2: {}
  konomi-collator-1: {}
  konomi-collator-2: {}
  konomi-parachain: {}

services:
#  nginx:
#    image: nginx:1.15-alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./config/nginx.conf.multi:/etc/nginx/conf.d/default.conf
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot

  konomi-relay-1:
    image: konominetwork/parachain:v0.1.0
    volumes:
      - konomi-relay-1:/tmp/konomi-rococo
    command: "polkadot --base-path /tmp/konomi-rococo --ws-external --no-beefy --chain /polkadot/rococo-single-custom.json --rpc-cors all --alice"

  konomi-relay-2:
    image: konominetwork/parachain:v0.1.0
    volumes:
      - konomi-relay-2:/tmp/konomi-rococo
    command: "polkadot --base-path /tmp/konomi-rococo --ws-external --no-beefy --chain /polkadot/rococo-single-custom.json --rpc-cors all --bob"

  konomi-collator-1:
    image: konominetwork/parachain:v0.1.0
    depends_on:
      - konomi-relay-1
      - konomi-relay-2
    volumes:
      - konomi-collator-1:/tmp/konomi-rococo
    command: "polkadot-collator --base-path /tmp/konomi-rococo --alice --force-authoring --parachain-id 18403 --ws-external --rpc-cors all -- --no-beefy --execution wasm --chain /polkadot/rococo-single-custom.json"

  konomi-collator-2:
    image: konominetwork/parachain:v0.1.0
    depends_on:
      - konomi-relay-1
      - konomi-relay-2
    volumes:
      - konomi-collator-2:/tmp/konomi-rococo
    command: "polkadot-collator --base-path /tmp/konomi-rococo --bob --force-authoring --parachain-id 18403 --ws-external --rpc-cors all -- --no-beefy --execution wasm --chain /polkadot/rococo-single-custom.json"

  konomi-parachain:
    image: konominetwork/parachain:v0.1.0
    depends_on:
      - konomi-relay-1
      - konomi-relay-2
    volumes:
      - konomi-parachain:/tmp/konomi-rococo
    command: "polkadot-collator --base-path /tmp/konomi-rococo --parachain-id 18403 --ws-external --rpc-cors all -- --no-beefy --execution wasm --chain /polkadot/rococo-single-custom.json"

  dot-feed:
    image: konominetwork/oracle-worker:v0.1.0
    depends_on:
      - konomi-parachain
    env_file:
      - ./docker/env/local/dot-feed

  eth-feed:
    image: konominetwork/oracle-worker:v0.1.0
    depends_on:
      - konomi-parachain
    env_file:
      - ./docker/env/local/eth-feed

  btc-feed:
    image: konominetwork/oracle-worker:v0.1.0
    depends_on:
      - konomi-parachain
    env_file:
      - ./docker/env/local/btc-feed

  indexer-service:
    image: konominetwork/indexer-service:v0.1.0
    depends_on:
      - konomi-parachain
    env_file:
      - ./docker/env/local/indexer
