[package]
name = "pallet-lending-rpc-runtime-api"
version = "3.0.0"
authors = ["Konomi team"]
edition = "2018"
license = "Apache-2.0"
description = "RPC runtime API for lending FRAME pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { version = '3.0.0', git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-std = { version = "3.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
serde = { version = "1.0.119", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", version = '3.0.0' }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" , version = '3.0.0' }

[features]
default = ["std"]
std = [
	"serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
]
