[package]
authors = ['Konomi Dev']
description = 'FRAME pallet for fixed rate lending'
edition = '2018'
license = 'Unlicense'
name = 'pallet-floating-rate-lend'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
serde = { version = "1.0.119", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }

pallet-traits = { path = '../traits', default-features = false, version = '3.0.0'}
rococo-parachain-primitives = { default-features = false, path = '../../primitives', version = '0.1.0'}
pallet-currencies = { path = '../currencies', default-features = false, version = '3.0.0' }

log = "0.4.13"

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-std/std',
    'sp-core/std',
    'sp-runtime/std',
    'pallet-traits/std',
    'serde',
]
