[package]
authors = ['Konomi Dev']
description = 'FRAME pallet for lending'
edition = '2018'
license = 'Unlicense'
name = 'pallet-currencies'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
log = "0.4.13"
serde = { version = "1.0.119", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }

orml-traits = { path = "../../../open-runtime-module-library/traits", default-features = false, version = '0.4.1-dev' }

# Local libs
polkadot-parachain-primitives = { default-features = false, path = '../../primitives', version = '0.1.0'}
pallet-traits = { path = '../traits', default-features = false, version = '3.0.0'}

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
orml-tokens = { path = "../../../open-runtime-module-library/tokens", default-features = false, version = '0.4.1-dev' }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-std/std',
    'sp-core/std',
    'sp-runtime/std',
    'serde',
]
