[package]
authors = ['Konomi Dev']
description = 'FRAME pallet for fixed rate lending'
edition = '2018'
license = 'Unlicense'
name = 'pallet-floating-rate-lend'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
serde = { version = "1.0.119", optional = true }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }

pallet-traits = { path = '../traits', default-features = false, version = '3.0.0'}
polkadot-parachain-primitives = { default-features = false, path = '../../primitives', version = '0.1.0'}
pallet-currencies = { path = '../currencies', default-features = false, version = '3.0.0' }
orml-traits = { path = "../../../open-runtime-module-library/traits", default-features = false, version = '0.4.1-dev' }
substrate-fixed = { git = 'https://github.com/encointer/substrate-fixed.git', branch = "master" }
log = "0.4.13"

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.3" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-std/std',
    'sp-core/std',
    'sp-runtime/std',
    'pallet-traits/std',
    'pallet-sudo/std',
    'serde',
]
