[package]
name = "pallet-lending-rpc"
version = "3.0.0"
authors = ["Konomi team"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/paritytech/substrate/"
description = "Node-specific RPC methods for interaction with lending."
readme = "README.md"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-rpc = { git = "https://github.com/paritytech/substrate", versi = '3.0.0', branch = "rococo-v1" }
sp-core = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

sp-std = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
serde = { version = "1.0.119", features = ["derive"] }
sp-runtime = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-api = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
pallet-lending-rpc-runtime-api = { version = "3.0.0", path = "./runtime-api" }
frame-support = { version = "3.0.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

[dev-dependencies]
serde_json = "1.0.41"
